# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Andre Xian Ming Chang
email: andrechang67@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  MSc. student in Electrical and Computer Engineering at Purdue West Lafayette
  under the supervision of Dr. Eugenio Culurciello
  Research interests in hardware acceleration for Recurrent neural networks
  (RNNs).
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://andrechang.github.io" # the base hostname & protocol for your site
github_username:  Andrechang

# Build settings
markdown: kramdown
