# Where things are
source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

gems:         [jekyll-paginate]

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     kramdown
highlighter:  rouge
lsi:          false
excerpt_separator: "\n\n"
toc_levels:   1..3 # TOC # 2015/11/29

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null

#Site config
title: Andrechang
description: Andrechang's blog
keywords: Deep Learning
url: http://andrechang.github.io
feed: /atom.xml
favicon: /images/shortcut.jpg

#Nav config
nav:
  - text: HOME
    url: /index.html
  - text: CATEGORIES
    url: /categories.html
#  - text: ARCHIVES
#    url: /archives.html
  - text: ABOUT ME
    url: /about.html
  - text: LINKS
    url: /links.html

#Author config
author:
    name: Andrechang
    email: andrechang67@gmail.com
    imageLink: /images/header.jpg
    simpleIntro: Ola
    detailIntro:
      <p>I am PhD. student at Purdue University working on hardware for machine learning/deep learning.</p>
<p>I am from Brazil so I will post tutorials and stuff in portugues as well.</p>
      <p>This blog is used as my research diary. I will store papers, websites, blogs and my study notes for various topics on electrical and computer engineering.</p>

     <p>Sou estudante de PhD. na universidade de Purdue e estou trabalhando em aprendizado de maquina.</p>
</p> Esse blog contera post em ingles e portugues </p>
      <p>Esse blog sera meu diario de pesquisa e irei guardar sites, artigos e notas de aulas sobre varios topicos de engenharia eletrica e computacao.</p>
      <p></p>

#You can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-rss
    url: /atom.xml
#  - class: icon-weibo
#    url: http://weibo.com/
  - class: icon-facebook
    url: https://www.facebook.com/
  - class: icon-github-alt
    url: https://github.com/Andrechang/
#  - class: icon-twitter
#    url: https://www.twitter.com/
#  - class: icon-google-plus
#    url: https://plus.google.com/116595571760191938657/about

#Links
customLinks:
  - item:
#    - text: EnSharing
#      url: http://ensharing.com/
#    - text: JOSHUA's BLOG
#      url: http://joshua881228.webfactional.com/
#    message: Friends
  - item:
#    - text: Caffe on github
#      url: https://github.com/BVLC/caffe
#    - text: Deep Learning Tutorials
#      url: http://deeplearning.net/tutorial/
#    - text: Deep Learning Reading List
#      url: http://deeplearning.net/reading-list/
#    message: About Deep Learning

#googleAnaly:
#  config: false
#  id: UA-58146229-1

#baidu tongji
#baiduTongji:
#  config: true
#  id:  9144251ce5a4f4019de4bc601b9b490b

#comment config
#disqus:
#  config: true
#  id: andrechang67

#duoshuo:
#  config: false
#  id: null

#baidu share config
#baiduShare:
#  config: false
